[package]
name = "advent_of_code_2022"
version = "0.1.5"
edition = "2021"
readme = "README.md"
license = "GPL-3"
authors = ["Tryton Van Meer <code@trytonvanmeer.dev>"]

[dependencies]
anyhow = "1"
clap = {version = "4", features = ["derive"]}
